trigger:
- main

pool:
  name: Default

steps:
- script: |
    echo "Hello from Azure DevOps CI Pipeline"
    python3 app.py
  displayName: "Run Python App"

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'output.txt'
    artifactName: 'my-artifact'
  displayName: "Publish Artifact"

